name: Build Docs

on:
  repository_dispatch:
    types: [build-docs]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
#      - uses: actions/checkout@v2
#        with:
#          path: main
      # checkout the triggering repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          repository: ${{ github.event.client_payload.repo }}
      - run: echo ${{ github.event.inputs }}
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 15
#          check-latest: true
#      - run: npm ci
#      - uses: netlify/actions/cli@master
#        with:
#          args: deploy --dir=site
#        env:
#          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
